# AI-Ops 配置文件

[ai]
default_model = "gemini"
timeout = 30

[ai.models.gemini]
type = "gemini"
api_key = "${GEMINI_API_KEY}"
base_url = "https://generativelanguage.googleapis.com/v1beta"
model = "gemini-2.5-flash"

[ai.models.openai]
type = "openai"
api_key = "${OPENAI_API_KEY}"
base_url = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o-mini"

[ai.models.glm]
type = "openai"
api_key = "${GLM_API_KEY}"
base_url = "https://open.bigmodel.cn/api/paas/v4"
model = "glm-4.5"

[logging]
level = "warn" # debug, info, warn, error

[weather]
api_host = "https://devapi.qweather.com"
api_key = "${QWEATHER_API_KEY}"

[rag]
enable = false  # 是否启用 RAG 工具，无知识库时可设为 false
api_host = "http://localhost:8000"
retrieval_k = 15
top_k = 5

[tools]
# 工具启用配置（sysinfo 为核心工具，始终启用）
echo = false     # Echo工具（调试用）
weather = false  # 天气工具（需要配置 QWEATHER_API_KEY）
rag = false      # RAG工具（需要启动RAG服务）