# AI-Ops 配置文件

[ai]
default_model = "gemini"
timeout = 30

[ai.models.gemini]
type = "gemini"
api_key = "${GEMINI_API_KEY}"
base_url = "https://generativelanguage.googleapis.com/v1beta"
model = "gemini-2.5-flash"

[ai.models.openai]
type = "openai"
api_key = "${OPENAI_API_KEY}"
base_url = "https://api.openai.com/v1/chat/completions"
model = "gpt-4o-mini"

[logging]
level = "warn"
format = "text"
output = "stdout"
file = ""

[weather]
api_host = "https://devapi.qweather.com"
api_key = "${QWEATHER_API_KEY}"